local file_api = require("cmakeseer.cmake.file_api")

describe("file_utils", function()
  describe("query_dir", function()
    it("returns the correct path", function()
      local result = file_api.query_dir(".")
      assert.are.equal("./.cmake/api/v1/query", result)
    end)
  end)
  describe("reply_dir", function()
    it("returns the correct path", function()
      local result = file_api.reply_dir(".")
      assert.are.equal("./.cmake/api/v1/reply", result)
    end)
  end)
end)
